--input_image_path: 'F:/tif_images/thyroid'

--output_image_path: 'F:/tif_images'

--input_xml_path: 'F:/tif_images/thyroid'

--palette_path: 'F:/palette.txt'

--crop_size: 900

--overlap: 300

--ignore_label_index: 255

--doing_list: ['hsil', 'scc', 'lsil']

--ignore_list: []

--ext_list: ['.tif']

